name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Install ZMQ
      run:  |
        wget https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz

        # Unpack tarball package
        tar xvzf zeromq-4.2.2.tar.gz

        # Install dependency
        sudo apt-get update && \
        sudo apt-get install -y libtool pkg-config build-essential autoconf automake uuid-dev

        # Create make file
        cd zeromq-4.2.2
        ./configure

        # Build and install(root permission only)
        sudo make install

        # Install zeromq driver on linux
        sudo ldconfig

      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: make test
